# Generated by Django 4.2.16 on 2024-10-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='info/', verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Referencias')),
                ('external_source', models.URLField(blank=True, null=True, verbose_name='Fuentes externas')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Noticia destacada')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='info/', verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('steps', models.TextField(blank=True, null=True, verbose_name='Pasos a seguir')),
                ('aditional_resources', models.URLField(blank=True, null=True, verbose_name='Recursos adicionales')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='info/', verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('features', models.TextField(verbose_name='Caracteristicas incluidas')),
                ('exclusions', models.TextField(blank=True, null=True, verbose_name='Exclusiones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeccionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitulo')),
                ('content', models.TextField(verbose_name='Pasos a seguir')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccionArticulo', to='informativos.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalServicioInfo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('features', models.TextField(verbose_name='Caracteristicas incluidas')),
                ('exclusions', models.TextField(blank=True, null=True, verbose_name='Exclusiones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical servicio info',
                'verbose_name_plural': 'historical servicio infos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSeccionArticulo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitulo')),
                ('content', models.TextField(verbose_name='Pasos a seguir')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='informativos.articulo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical seccion articulo',
                'verbose_name_plural': 'historical seccion articulos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGuia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('steps', models.TextField(blank=True, null=True, verbose_name='Pasos a seguir')),
                ('aditional_resources', models.URLField(blank=True, null=True, verbose_name='Recursos adicionales')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical guia',
                'verbose_name_plural': 'historical guias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalArticulo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Referencias')),
                ('external_source', models.URLField(blank=True, null=True, verbose_name='Fuentes externas')),
                ('publication_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de publicacion')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Noticia destacada')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical articulo',
                'verbose_name_plural': 'historical articulos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
