# Generated by Django 4.2.16 on 2024-12-09 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import informativos.base
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description_short', models.TextField(blank=True, default='N/A', verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, default='', upload_to='info/', validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones')),
                ('references', models.TextField(blank=True, default='N/A', verbose_name='Referencias')),
                ('external_source', models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', verbose_name='Fuentes externas')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Noticia destacada')),
            ],
            options={
                'permissions': [('can_view_articulo', 'Can view articulo'), ('can_edit_articulo', 'Can edit articulo')],
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description_short', models.TextField(blank=True, default='N/A', verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, default='', upload_to='info/', validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones')),
                ('steps', models.TextField(blank=True, default='N/A', verbose_name='Pasos a seguir')),
                ('aditional_resources', models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', verbose_name='Recursos adicionales')),
            ],
            options={
                'permissions': [('can_view_guia', 'Can view guia'), ('can_edit_guia', 'Can edit guia')],
            },
        ),
        migrations.CreateModel(
            name='ServicioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description_short', models.TextField(blank=True, default='N/A', verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, default='', upload_to='info/', validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones')),
                ('features', models.TextField(verbose_name='Caracteristicas incluidas')),
                ('exclusions', models.TextField(blank=True, default='N/A', verbose_name='Exclusiones')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'permissions': [('can_view_servicioInfo', 'Can view servicioInfo'), ('can_edit_servicioInfo', 'Can edit servicioInfo')],
            },
        ),
        migrations.CreateModel(
            name='SeccionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtitulo')),
                ('content', models.TextField(blank=True, verbose_name='contenido')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccionArticulo', to='informativos.articulo')),
            ],
            options={
                'permissions': [('can_view_deudo', 'Can view deudo'), ('can_edit_deudo', 'Can edit deudo')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalServicioInfo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description_short', models.TextField(blank=True, default='N/A', verbose_name='Descripcion')),
                ('image', models.TextField(blank=True, default='', max_length=100, validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones')),
                ('features', models.TextField(verbose_name='Caracteristicas incluidas')),
                ('exclusions', models.TextField(blank=True, default='N/A', verbose_name='Exclusiones')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical servicio info',
                'verbose_name_plural': 'historical servicio infos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSeccionArticulo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtitulo')),
                ('content', models.TextField(blank=True, verbose_name='contenido')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='informativos.articulo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical seccion articulo',
                'verbose_name_plural': 'historical seccion articulos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGuia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description_short', models.TextField(blank=True, default='N/A', verbose_name='Descripcion')),
                ('image', models.TextField(blank=True, default='', max_length=100, validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones')),
                ('steps', models.TextField(blank=True, default='N/A', verbose_name='Pasos a seguir')),
                ('aditional_resources', models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', verbose_name='Recursos adicionales')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical guia',
                'verbose_name_plural': 'historical guias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalArticulo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description_short', models.TextField(blank=True, default='N/A', verbose_name='Descripcion')),
                ('image', models.TextField(blank=True, default='', max_length=100, validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='Creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizacion')),
                ('description', models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones')),
                ('references', models.TextField(blank=True, default='N/A', verbose_name='Referencias')),
                ('external_source', models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', verbose_name='Fuentes externas')),
                ('publication_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de publicacion')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Noticia destacada')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical articulo',
                'verbose_name_plural': 'historical articulos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
