# Generated by Django 4.2.16 on 2024-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion breve'),
        ),
        migrations.AddField(
            model_name='guia',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion breve'),
        ),
        migrations.AddField(
            model_name='historicalarticulo',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion breve'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion breve'),
        ),
        migrations.AddField(
            model_name='historicalseccionarticulo',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='historicalseccionarticulo',
            name='loadDate',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creacion'),
        ),
        migrations.AddField(
            model_name='historicalseccionarticulo',
            name='updateDate',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizacion'),
        ),
        migrations.AddField(
            model_name='historicalservicioinfo',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion breve'),
        ),
        migrations.AddField(
            model_name='seccionarticulo',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='seccionarticulo',
            name='loadDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creacion'),
        ),
        migrations.AddField(
            model_name='seccionarticulo',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizacion'),
        ),
        migrations.AddField(
            model_name='servicioinfo',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion breve'),
        ),
    ]
