# Generated by Django 4.2.16 on 2024-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0002_articulo_description_short_guia_description_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicioinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='servicioinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
