# Generated by Django 4.2.16 on 2024-10-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0003_historicalservicioinfo_price_servicioinfo_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'permissions': [('can_view_articulo', 'Can view articulo'), ('can_edit_articulo', 'Can edit articulo')]},
        ),
        migrations.AlterModelOptions(
            name='guia',
            options={'permissions': [('can_view_guia', 'Can view guia'), ('can_edit_guia', 'Can edit guia')]},
        ),
        migrations.AlterModelOptions(
            name='seccionarticulo',
            options={'permissions': [('can_view_deudo', 'Can view deudo'), ('can_edit_deudo', 'Can edit deudo')]},
        ),
        migrations.AlterModelOptions(
            name='servicioinfo',
            options={'permissions': [('can_view_servicioInfo', 'Can view servicioInfo'), ('can_edit_servicioInfo', 'Can edit servicioInfo')]},
        ),
    ]
