# Generated by Django 4.2.16 on 2024-10-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0004_alter_articulo_options_alter_guia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseccionarticulo',
            name='content',
            field=models.TextField(verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='seccionarticulo',
            name='content',
            field=models.TextField(verbose_name='contenido'),
        ),
    ]
