# Generated by Django 4.2.16 on 2024-12-03 08:34

from django.db import migrations, models
import informativos.base


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0006_alter_articulo_image_alter_guia_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='description_short',
            field=models.TextField(blank=True, default='N/A', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='external_source',
            field=models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', verbose_name='Fuentes externas'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='info/', validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='references',
            field=models.TextField(blank=True, default='N/A', verbose_name='Referencias'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='aditional_resources',
            field=models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', verbose_name='Recursos adicionales'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='description_short',
            field=models.TextField(blank=True, default='N/A', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='info/', validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='steps',
            field=models.TextField(blank=True, default='N/A', verbose_name='Pasos a seguir'),
        ),
        migrations.AlterField(
            model_name='historicalarticulo',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='historicalarticulo',
            name='description_short',
            field=models.TextField(blank=True, default='N/A', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='historicalarticulo',
            name='external_source',
            field=models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', verbose_name='Fuentes externas'),
        ),
        migrations.AlterField(
            model_name='historicalarticulo',
            name='image',
            field=models.TextField(blank=True, default='', max_length=100, validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalarticulo',
            name='references',
            field=models.TextField(blank=True, default='N/A', verbose_name='Referencias'),
        ),
        migrations.AlterField(
            model_name='historicalguia',
            name='aditional_resources',
            field=models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', verbose_name='Recursos adicionales'),
        ),
        migrations.AlterField(
            model_name='historicalguia',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='historicalguia',
            name='description_short',
            field=models.TextField(blank=True, default='N/A', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='historicalguia',
            name='image',
            field=models.TextField(blank=True, default='', max_length=100, validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalguia',
            name='steps',
            field=models.TextField(blank=True, default='N/A', verbose_name='Pasos a seguir'),
        ),
        migrations.AlterField(
            model_name='historicalseccionarticulo',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='historicalservicioinfo',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='historicalservicioinfo',
            name='description_short',
            field=models.TextField(blank=True, default='N/A', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='historicalservicioinfo',
            name='exclusions',
            field=models.TextField(blank=True, default='N/A', verbose_name='Exclusiones'),
        ),
        migrations.AlterField(
            model_name='historicalservicioinfo',
            name='image',
            field=models.TextField(blank=True, default='', max_length=100, validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalservicioinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='seccionarticulo',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='servicioinfo',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='servicioinfo',
            name='description_short',
            field=models.TextField(blank=True, default='N/A', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='servicioinfo',
            name='exclusions',
            field=models.TextField(blank=True, default='N/A', verbose_name='Exclusiones'),
        ),
        migrations.AlterField(
            model_name='servicioinfo',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='info/', validators=[informativos.base.validar_tamano_imagen], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='servicioinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
    ]
