# Generated by Django 4.2.16 on 2024-09-25 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('blockName', models.CharField(max_length=3, verbose_name='lote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tumba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('nicheNumber', models.IntegerField(max_length=4, verbose_name='tumba')),
                ('nicheType', models.CharField(choices=[('T', 'Tumba de tierra'), ('E', 'Tumba extramuros')], max_length=1, verbose_name='tipo')),
                ('nameLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumbaLote', to='tumba.lote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisponibleTumba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('startDate', models.DateTimeField(verbose_name='inicio')),
                ('endDate', models.DateTimeField(verbose_name='vence')),
                ('numberTumba', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disponibleTumba', to='tumba.tumba')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
