# Generated by Django 4.2.16 on 2024-09-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumba',
            name='nicheNumber',
            field=models.IntegerField(verbose_name='tumba'),
        ),
    ]
