# Generated by Django 4.2.16 on 2024-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0002_alter_tumba_nichenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='clasificacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='lote',
            name='columnas',
            field=models.IntegerField(null=True, verbose_name='Nuero de columnas'),
        ),
        migrations.AddField(
            model_name='lote',
            name='filas',
            field=models.IntegerField(null=True, verbose_name='Nuero de filas'),
        ),
        migrations.AddField(
            model_name='lote',
            name='limite',
            field=models.IntegerField(null=True, verbose_name='Limite de espacio'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='blockName',
            field=models.IntegerField(verbose_name='bloque'),
        ),
    ]
