# Generated by Django 4.2.16 on 2024-09-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0003_lote_clasificacion_lote_columnas_lote_filas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='clasificacion',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='columnas',
            field=models.IntegerField(verbose_name='Nuero de columnas'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='filas',
            field=models.IntegerField(verbose_name='Nuero de filas'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='limite',
            field=models.IntegerField(verbose_name='Limite de espacio'),
        ),
    ]
