# Generated by Django 4.2.16 on 2024-09-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0005_disponibletumba_modified_by_lote_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibletumba',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='tumba',
            name='modified_by',
        ),
    ]
