# Generated by Django 4.2.16 on 2024-09-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0007_historicaltumba_historicallote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallote',
            name='numbersblock',
            field=models.IntegerField(null=True, verbose_name='numero tipo'),
        ),
        migrations.AddField(
            model_name='lote',
            name='numbersblock',
            field=models.IntegerField(null=True, verbose_name='numero tipo'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='clasificacion',
            field=models.CharField(max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='clasificacion',
            field=models.CharField(max_length=3, verbose_name='Tipo'),
        ),
    ]
