# Generated by Django 4.2.16 on 2024-09-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0008_historicallote_numbersblock_lote_numbersblock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallote',
            old_name='clasificacion',
            new_name='typeblock',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='clasificacion',
            new_name='typeblock',
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='numbersblock',
            field=models.IntegerField(null=True, verbose_name='numero de tipo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numbersblock',
            field=models.IntegerField(null=True, verbose_name='numero de tipo'),
        ),
    ]
