# Generated by Django 4.2.16 on 2024-09-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0009_rename_clasificacion_historicallote_typeblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltumba',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tumba',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
