# Generated by Django 4.2.16 on 2024-09-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0010_historicaltumba_available_tumba_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibletumba',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historicaldisponibletumba',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historicallote',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historicaltumba',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tumba',
            old_name='decription',
            new_name='description',
        ),
    ]
