# Generated by Django 4.2.16 on 2024-10-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0011_rename_decription_disponibletumba_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldisponibletumba',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldisponibletumba',
            name='numberTumba',
        ),
        migrations.DeleteModel(
            name='DisponibleTumba',
        ),
        migrations.DeleteModel(
            name='HistoricalDisponibleTumba',
        ),
    ]
