# Generated by Django 4.2.16 on 2024-12-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0012_remove_historicaldisponibletumba_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallote',
            name='height',
            field=models.FloatField(blank='true', default=0, verbose_name='alto'),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='rotation',
            field=models.FloatField(blank='true', default=0, verbose_name='rotacion'),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='text_x',
            field=models.FloatField(blank='true', default=0, verbose_name='text x'),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='text_y',
            field=models.FloatField(blank='true', default=0, verbose_name='text y'),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='width',
            field=models.FloatField(blank='true', default=0, verbose_name='ancho'),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='x',
            field=models.FloatField(blank='true', default=0, verbose_name='x'),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='y',
            field=models.FloatField(blank='true', default=0, verbose_name='y'),
        ),
        migrations.AddField(
            model_name='lote',
            name='height',
            field=models.FloatField(blank='true', default=0, verbose_name='alto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='rotation',
            field=models.FloatField(blank='true', default=0, verbose_name='rotacion'),
        ),
        migrations.AddField(
            model_name='lote',
            name='text_x',
            field=models.FloatField(blank='true', default=0, verbose_name='text x'),
        ),
        migrations.AddField(
            model_name='lote',
            name='text_y',
            field=models.FloatField(blank='true', default=0, verbose_name='text y'),
        ),
        migrations.AddField(
            model_name='lote',
            name='width',
            field=models.FloatField(blank='true', default=0, verbose_name='ancho'),
        ),
        migrations.AddField(
            model_name='lote',
            name='x',
            field=models.FloatField(blank='true', default=0, verbose_name='x'),
        ),
        migrations.AddField(
            model_name='lote',
            name='y',
            field=models.FloatField(blank='true', default=0, verbose_name='y'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='blockName',
            field=models.IntegerField(verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='columnas',
            field=models.IntegerField(verbose_name='Numero de columnas'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='filas',
            field=models.IntegerField(verbose_name='Numero de filas'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='numbersblock',
            field=models.IntegerField(blank=True, default=0, verbose_name='numero de tipo'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='typeblock',
            field=models.CharField(max_length=3, verbose_name='Tipo de Bloque'),
        ),
        migrations.AlterField(
            model_name='historicaltumba',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='blockName',
            field=models.IntegerField(verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='columnas',
            field=models.IntegerField(verbose_name='Numero de columnas'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='filas',
            field=models.IntegerField(verbose_name='Numero de filas'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numbersblock',
            field=models.IntegerField(blank=True, default=0, verbose_name='numero de tipo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='typeblock',
            field=models.CharField(max_length=3, verbose_name='Tipo de Bloque'),
        ),
        migrations.AlterField(
            model_name='tumba',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
    ]
