# Generated by Django 4.2.16 on 2024-12-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0014_alter_historicallote_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallote',
            name='height',
        ),
        migrations.RemoveField(
            model_name='historicallote',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='historicallote',
            name='text_x',
        ),
        migrations.RemoveField(
            model_name='historicallote',
            name='text_y',
        ),
        migrations.RemoveField(
            model_name='historicallote',
            name='width',
        ),
        migrations.RemoveField(
            model_name='historicallote',
            name='x',
        ),
        migrations.RemoveField(
            model_name='historicallote',
            name='y',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='height',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='text_x',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='text_y',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='width',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='x',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='y',
        ),
    ]
