# Generated by Django 4.2.16 on 2024-12-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0016_historicallote_height_historicallote_rotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallote',
            name='trans_x',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Translate X'),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='trans_y',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Translate Y'),
        ),
        migrations.AddField(
            model_name='lote',
            name='trans_x',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Translate X'),
        ),
        migrations.AddField(
            model_name='lote',
            name='trans_y',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Translate Y'),
        ),
    ]
