# Generated by Django 4.2.16 on 2024-12-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0017_historicallote_trans_x_historicallote_trans_y_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallote',
            old_name='trans_x',
            new_name='trans_r_x',
        ),
        migrations.RenameField(
            model_name='historicallote',
            old_name='trans_y',
            new_name='trans_r_y',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='trans_x',
            new_name='trans_r_x',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='trans_y',
            new_name='trans_r_y',
        ),
        migrations.RemoveField(
            model_name='historicallote',
            name='height',
        ),
        migrations.RemoveField(
            model_name='historicallote',
            name='width',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='height',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='width',
        ),
        migrations.AddField(
            model_name='historicallote',
            name='trans_t_x',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Translate X'),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='trans_t_y',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Translate Y'),
        ),
        migrations.AddField(
            model_name='lote',
            name='trans_t_x',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Translate X'),
        ),
        migrations.AddField(
            model_name='lote',
            name='trans_t_y',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Translate Y'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='text_x',
            field=models.FloatField(blank='true', default=0.0, verbose_name='text x'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='text_y',
            field=models.FloatField(blank='true', default=0.0, verbose_name='text y'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='text_x',
            field=models.FloatField(blank='true', default=0.0, verbose_name='text x'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='text_y',
            field=models.FloatField(blank='true', default=0.0, verbose_name='text y'),
        ),
    ]
