# Generated by Django 4.2.16 on 2024-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0018_rename_trans_x_historicallote_trans_r_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallote',
            name='text_x',
            field=models.IntegerField(blank='true', default=0, verbose_name='text x'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='text_y',
            field=models.IntegerField(blank='true', default=0, verbose_name='text y'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='text_x',
            field=models.IntegerField(blank='true', default=0, verbose_name='text x'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='text_y',
            field=models.IntegerField(blank='true', default=0, verbose_name='text y'),
        ),
    ]
