# Generated by Django 4.2.16 on 2024-12-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0020_alter_historicallote_rotation_alter_lote_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallote',
            name='trans_r_x',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Translate X'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='trans_r_y',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Translate Y'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='trans_t_x',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Translate X'),
        ),
        migrations.AlterField(
            model_name='historicallote',
            name='trans_t_y',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Translate Y'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='trans_r_x',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Translate X'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='trans_r_y',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Translate Y'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='trans_t_x',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Translate X'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='trans_t_y',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Translate Y'),
        ),
    ]
