# Generated by Django 4.2.16 on 2024-12-24 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0022_alter_historicallote_blockname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltumba',
            name='nicheNumber',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='tumba'),
        ),
        migrations.AlterField(
            model_name='tumba',
            name='nicheNumber',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='tumba'),
        ),
    ]
