# Generated by Django 4.2.16 on 2024-12-24 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0023_alter_historicaltumba_nichenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallote',
            name='blockName',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='blockName',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Lote'),
        ),
    ]
