# Generated by Django 4.2.16 on 2024-09-25 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tumba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200, verbose_name='nombres')),
                ('last_names', models.CharField(max_length=200, verbose_name='apellidos')),
                ('idNumber', models.CharField(max_length=10, unique=True, verbose_name='cedula')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='direccion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Difunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200, verbose_name='nombres')),
                ('last_names', models.CharField(max_length=200, verbose_name='apellidos')),
                ('idNumber', models.CharField(max_length=10, unique=True, verbose_name='cedula')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('requestNumber', models.CharField(max_length=20, unique=True, verbose_name='solicitud')),
                ('deudo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='difuntoDeudo', to='difunto.deudo')),
                ('tumba', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='difuntoTumba', to='tumba.tumba')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
