# Generated by Django 4.2.16 on 2024-09-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difunto', '0002_deudo_modified_by_difunto_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudo',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='difunto',
            name='modified_by',
        ),
    ]
