# Generated by Django 4.2.16 on 2024-09-28 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tumba', '0007_historicaltumba_historicallote_and_more'),
        ('difunto', '0003_remove_deudo_modified_by_remove_difunto_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDifunto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('names', models.CharField(max_length=200, verbose_name='nombres')),
                ('last_names', models.CharField(max_length=200, verbose_name='apellidos')),
                ('idNumber', models.CharField(db_index=True, max_length=10, verbose_name='cedula')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('requestNumber', models.CharField(db_index=True, max_length=20, verbose_name='solicitud')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deudo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='difunto.deudo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tumba', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tumba.tumba')),
            ],
            options={
                'verbose_name': 'historical difunto',
                'verbose_name_plural': 'historical difuntos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeudo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('names', models.CharField(max_length=200, verbose_name='nombres')),
                ('last_names', models.CharField(max_length=200, verbose_name='apellidos')),
                ('idNumber', models.CharField(db_index=True, max_length=10, verbose_name='cedula')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='direccion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical deudo',
                'verbose_name_plural': 'historical deudos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
