# Generated by Django 4.2.16 on 2024-09-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difunto', '0004_historicaldifunto_historicaldeudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deudo',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='difunto',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historicaldeudo',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historicaldifunto',
            old_name='decription',
            new_name='description',
        ),
    ]
