# Generated by Django 4.2.16 on 2024-09-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difunto', '0005_rename_decription_deudo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudo',
            name='tipo',
            field=models.CharField(choices=[('Allegado', 'Familiar cercano'), ('Familiar', 'Miembro de la familia'), ('Conocido', 'Conocido del fallecido')], max_length=50, null=True, verbose_name='tipo relacion'),
        ),
        migrations.AddField(
            model_name='historicaldeudo',
            name='tipo',
            field=models.CharField(choices=[('Allegado', 'Familiar cercano'), ('Familiar', 'Miembro de la familia'), ('Conocido', 'Conocido del fallecido')], max_length=50, null=True, verbose_name='tipo relacion'),
        ),
    ]
