# Generated by Django 4.2.16 on 2024-10-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0011_rename_decription_disponibletumba_description_and_more'),
        ('difunto', '0006_deudo_tipo_historicaldeudo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difunto',
            name='tumba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='difuntoTumba', to='tumba.tumba'),
        ),
    ]
