# Generated by Django 4.2.16 on 2024-10-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difunto', '0007_alter_difunto_tumba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deudo',
            options={'permissions': [('can_view_deudo', 'Can view deudo'), ('can_edit_deudo', 'Can edit deudo')]},
        ),
        migrations.AlterModelOptions(
            name='difunto',
            options={'permissions': [('can_view_difunto', 'Can view difunto'), ('can_edit_difunto', 'Can edit difunto')]},
        ),
    ]
