# Generated by Django 4.2.16 on 2024-12-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0023_alter_historicaltumba_nichenumber_and_more'),
        ('difunto', '0009_alter_deudo_address_alter_deudo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difunto',
            name='tumba',
            field=models.ForeignKey(default=6000, on_delete=django.db.models.deletion.DO_NOTHING, related_name='difuntoTumba', to='tumba.tumba'),
        ),
    ]
