# Generated by Django 4.2.16 on 2024-12-25 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0024_alter_historicallote_blockname_alter_lote_blockname'),
        ('difunto', '0010_alter_difunto_tumba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difunto',
            name='tumba',
            field=models.ForeignKey(blank=True, default=6000, on_delete=django.db.models.deletion.DO_NOTHING, related_name='difuntoTumba', to='tumba.tumba'),
        ),
    ]
