# Generated by Django 4.2.16 on 2024-10-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicio', '0008_alter_ceremonia_names_and_more'),
        ('difunto', '0006_deudo_tipo_historicaldeudo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseObituario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalObituario',
            fields=[
                ('baseobituario_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='obituarios.baseobituario')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('obituary_detail', models.TextField(verbose_name='Detalle del difunto')),
                ('cementery', models.CharField(blank=True, max_length=200, null=True, verbose_name='lugar de la ceremonia')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='lugar de la ceremonia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deceased', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='difunto.difunto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical obituario',
                'verbose_name_plural': 'historical obituarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Obituario',
            fields=[
                ('baseobituario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='obituarios.baseobituario')),
                ('obituary_detail', models.TextField(verbose_name='Detalle del difunto')),
                ('cementery', models.CharField(blank=True, max_length=200, null=True, verbose_name='lugar de la ceremonia')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='lugar de la ceremonia')),
                ('deceased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obituarioDifunto', to='difunto.difunto')),
            ],
            bases=('obituarios.baseobituario',),
        ),
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('baseobituario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='obituarios.baseobituario')),
                ('names', models.CharField(max_length=200, verbose_name='Nombre autor')),
                ('relationship', models.CharField(blank=True, max_length=200, null=True, verbose_name='Relacion con el difunto')),
                ('text', models.TextField(verbose_name='Recuerdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='memories/', verbose_name='Imagen opcional')),
                ('obituary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoriaObituario', to='obituarios.obituario')),
            ],
            bases=('obituarios.baseobituario',),
        ),
        migrations.CreateModel(
            name='HistoricalMemoria',
            fields=[
                ('baseobituario_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='obituarios.baseobituario')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('names', models.CharField(max_length=200, verbose_name='Nombre autor')),
                ('relationship', models.CharField(blank=True, max_length=200, null=True, verbose_name='Relacion con el difunto')),
                ('text', models.TextField(verbose_name='Recuerdo')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen opcional')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obituary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='obituarios.obituario')),
            ],
            options={
                'verbose_name': 'historical memoria',
                'verbose_name_plural': 'historical memorias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEtapasObituario',
            fields=[
                ('baseobituario_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='obituarios.baseobituario')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='actualizacion')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('stage_ceremony', models.CharField(choices=[('Velacion', 'Velación'), ('Misa', 'Misa'), ('Recepcion', 'Recepción'), ('Entrega_cenizas', 'Entrega de las cenizas'), ('Lectura_recuerdos', 'Lectura de recuerdos'), ('Celebracion_vida', 'Celebración de vida')], max_length=100, verbose_name='Etapas de las ceremonias')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='lugar de la ceremonia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ceremony', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicio.ceremonia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obituary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='obituarios.obituario')),
            ],
            options={
                'verbose_name': 'historical etapas obituario',
                'verbose_name_plural': 'historical etapas obituarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EtapasObituario',
            fields=[
                ('baseobituario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='obituarios.baseobituario')),
                ('stage_ceremony', models.CharField(choices=[('Velacion', 'Velación'), ('Misa', 'Misa'), ('Recepcion', 'Recepción'), ('Entrega_cenizas', 'Entrega de las cenizas'), ('Lectura_recuerdos', 'Lectura de recuerdos'), ('Celebracion_vida', 'Celebración de vida')], max_length=100, verbose_name='Etapas de las ceremonias')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='lugar de la ceremonia')),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapasCeremonia', to='servicio.ceremonia')),
                ('obituary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapasObituario', to='obituarios.obituario')),
            ],
            bases=('obituarios.baseobituario',),
        ),
    ]
