# Generated by Django 4.2.16 on 2024-10-16 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0010_remove_historicalservicio_deudo_and_more'),
        ('obituarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapasobituario',
            options={'permissions': [('can_view_etapasObituario', 'Can view etapasObituario'), ('can_edit_etapasObituario', 'Can edit etapasObituario')]},
        ),
        migrations.AlterModelOptions(
            name='memoria',
            options={'permissions': [('can_view_memoria', 'Can view memoria'), ('can_edit_memoria', 'Can edit memoria')]},
        ),
        migrations.AlterModelOptions(
            name='obituario',
            options={'permissions': [('can_view_obituario', 'Can view obituario'), ('can_edit_obituario', 'Can edit obituario')]},
        ),
        migrations.AlterField(
            model_name='etapasobituario',
            name='ceremony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapasCeremonia', to='servicio.servicio'),
        ),
        migrations.AlterField(
            model_name='historicaletapasobituario',
            name='ceremony',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicio.servicio'),
        ),
    ]
