# Generated by Django 4.2.16 on 2024-10-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obituarios', '0002_alter_etapasobituario_options_alter_memoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobituario',
            name='cementery',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='cemeterio'),
        ),
        migrations.AlterField(
            model_name='historicalobituario',
            name='obituary_detail',
            field=models.TextField(verbose_name='Detalle del obituario'),
        ),
        migrations.AlterField(
            model_name='obituario',
            name='cementery',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='cemeterio'),
        ),
        migrations.AlterField(
            model_name='obituario',
            name='obituary_detail',
            field=models.TextField(verbose_name='Detalle del obituario'),
        ),
    ]
