# Generated by Django 4.2.16 on 2024-10-24 01:07

from django.db import migrations, models
import obituarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('obituarios', '0003_alter_historicalobituario_cementery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmemoria',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[obituarios.models.validar_tamano_imagen], verbose_name='Imagen opcional'),
        ),
        migrations.AlterField(
            model_name='memoria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memories/', validators=[obituarios.models.validar_tamano_imagen], verbose_name='Imagen opcional'),
        ),
    ]
