# Generated by Django 4.2.16 on 2024-12-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obituarios', '0003_historicalobituario_date_born_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapasobituario',
            name='ceremony',
        ),
        migrations.RemoveField(
            model_name='historicaletapasobituario',
            name='ceremony',
        ),
    ]
