# Generated by Django 4.2.16 on 2024-10-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obituarios', '0005_historicalobituario_name_obituario_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapasobituario',
            old_name='stage_type',
            new_name='stage_ceremony',
        ),
        migrations.RenameField(
            model_name='historicaletapasobituario',
            old_name='stage_type',
            new_name='stage_ceremony',
        ),
    ]
