# Generated by Django 4.2.16 on 2024-09-25 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tumba', '0001_initial'),
        ('difunto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('startDate', models.DateTimeField(verbose_name='inicio')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name='vecimiento')),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicioDifunto', to='difunto.difunto')),
                ('numberTomb', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicioTumba', to='tumba.tumba')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ceremonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadDate', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('names', models.CharField(choices=[('Cremacion', 'Cremación'), ('Inhumacion', 'Inhumación'), ('Exhumacion', 'Exhumación')], max_length=50, verbose_name='tipo')),
                ('date', models.DateTimeField(verbose_name='fecha')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceremoniaServicio', to='servicio.servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
