# Generated by Django 4.2.16 on 2024-09-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_ceremonia_modified_by_servicio_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceremonia',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='modified_by',
        ),
    ]
