# Generated by Django 4.2.16 on 2024-09-28 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('difunto', '0004_historicaldifunto_historicaldeudo'),
        ('tumba', '0007_historicaltumba_historicallote_and_more'),
        ('servicio', '0003_remove_ceremonia_modified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServicio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('startDate', models.DateTimeField(verbose_name='inicio')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name='vecimiento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deceased', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='difunto.difunto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('numberTomb', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tumba.tumba')),
            ],
            options={
                'verbose_name': 'historical servicio',
                'verbose_name_plural': 'historical servicios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCeremonia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('loadDate', models.DateTimeField(blank=True, editable=False, verbose_name='creacion')),
                ('updateDate', models.DateTimeField(blank=True, editable=False, verbose_name='actualizacion')),
                ('decription', models.TextField(blank=True, max_length=300, null=True, verbose_name='observaciones')),
                ('names', models.CharField(choices=[('Cremacion', 'Cremación'), ('Inhumacion', 'Inhumación'), ('Exhumacion', 'Exhumación')], max_length=50, verbose_name='tipo')),
                ('date', models.DateTimeField(verbose_name='fecha')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('servicios', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicio.servicio')),
            ],
            options={
                'verbose_name': 'historical ceremonia',
                'verbose_name_plural': 'historical ceremonias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
