# Generated by Django 4.2.16 on 2024-09-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_historicalservicio_historicalceremonia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceremonia',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historicalceremonia',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historicalservicio',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='decription',
            new_name='description',
        ),
    ]
