# Generated by Django 4.2.16 on 2024-10-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0011_rename_decription_disponibletumba_description_and_more'),
        ('servicio', '0006_historicalservicio_deudo_servicio_deudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='numberTomb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicioTumba', to='tumba.tumba'),
        ),
    ]
