# Generated by Django 4.2.16 on 2024-10-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_alter_servicio_numbertomb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremonia',
            name='names',
            field=models.CharField(choices=[('Cremacion', 'Cremación'), ('Inhumacion', 'Inhumación'), ('Exhumacion', 'Exhumación'), ('Conmemoracion', 'Conmemoración'), ('Mantenimiento', 'Mantenimiento')], max_length=50, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='historicalceremonia',
            name='names',
            field=models.CharField(choices=[('Cremacion', 'Cremación'), ('Inhumacion', 'Inhumación'), ('Exhumacion', 'Exhumación'), ('Conmemoracion', 'Conmemoración'), ('Mantenimiento', 'Mantenimiento')], max_length=50, verbose_name='tipo'),
        ),
    ]
