# Generated by Django 4.2.16 on 2024-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_alter_ceremonia_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremonia',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='ceremonia',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='ceremonia',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='historicalceremonia',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='historicalceremonia',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='historicalceremonia',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
    ]
