# Generated by Django 4.2.16 on 2024-10-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obituarios', '0002_alter_etapasobituario_options_alter_memoria_options_and_more'),
        ('servicio', '0010_remove_historicalservicio_deudo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalceremonia',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalceremonia',
            name='servicios',
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'permissions': [('can_view_servicio', 'Can view servicio'), ('can_edit_servicio', 'Can edit servicio')]},
        ),
        migrations.AddField(
            model_name='historicalservicio',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='historicalservicio',
            name='ceremony',
            field=models.CharField(blank=True, choices=[('Cremacion', 'Cremación'), ('Inhumacion', 'Inhumación'), ('Exhumacion', 'Exhumación'), ('Conmemoracion', 'Conmemoración'), ('Mantenimiento', 'Mantenimiento')], max_length=50, null=True, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='historicalservicio',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='historicalservicio',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ceremony',
            field=models.CharField(blank=True, choices=[('Cremacion', 'Cremación'), ('Inhumacion', 'Inhumación'), ('Exhumacion', 'Exhumación'), ('Conmemoracion', 'Conmemoración'), ('Mantenimiento', 'Mantenimiento')], max_length=50, null=True, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.DeleteModel(
            name='Ceremonia',
        ),
        migrations.DeleteModel(
            name='HistoricalCeremonia',
        ),
    ]
