# Generated by Django 4.2.16 on 2024-12-03 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tumba', '0013_historicallote_height_historicallote_rotation_and_more'),
        ('servicio', '0011_remove_historicalceremonia_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicio',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.1, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='historicalservicio',
            name='ceremony',
            field=models.CharField(blank=True, choices=[('Cremacion', 'Cremación'), ('Inhumacion', 'Inhumación'), ('Exhumacion', 'Exhumación'), ('Conmemoracion', 'Conmemoración'), ('Mantenimiento', 'Mantenimiento')], default='Inhumacion', max_length=50, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='historicalservicio',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='historicalservicio',
            name='endDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='vecimiento'),
        ),
        migrations.AlterField(
            model_name='historicalservicio',
            name='numberTomb',
            field=models.ForeignKey(blank=True, db_constraint=False, default=6000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tumba.tumba'),
        ),
        migrations.AlterField(
            model_name='historicalservicio',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.1, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='ceremony',
            field=models.CharField(blank=True, choices=[('Cremacion', 'Cremación'), ('Inhumacion', 'Inhumación'), ('Exhumacion', 'Exhumación'), ('Conmemoracion', 'Conmemoración'), ('Mantenimiento', 'Mantenimiento')], default='Inhumacion', max_length=50, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='description',
            field=models.TextField(blank=True, default='N/A', max_length=300, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='endDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='vecimiento'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='numberTomb',
            field=models.ForeignKey(blank=True, default=6000, on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicioTumba', to='tumba.tumba'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de pago'),
        ),
    ]
