# Generated by Django 4.2.16 on 2024-12-24 22:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0012_alter_historicalservicio_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicio',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.10'), max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.10'), max_digits=10, verbose_name='Monto'),
        ),
    ]
