# Generated by Django 4.2.16 on 2024-12-24 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0013_alter_historicalservicio_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicio',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='vecimiento'),
        ),
        migrations.AlterField(
            model_name='historicalservicio',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='vecimiento'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio'),
        ),
    ]
