# Generated by Django 4.2.16 on 2024-10-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaliglesia',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='iglesia',
            name='facebook_url',
        ),
    ]
