# Generated by Django 4.2.16 on 2024-10-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0002_remove_historicaliglesia_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iglesia',
            options={'permissions': [('can_view_iglesia', 'Can view iglesia'), ('can_edit_iglesia', 'Can edit iglesia')]},
        ),
        migrations.AlterModelOptions(
            name='linkredsocial',
            options={'permissions': [('can_view_linkRedSocial', 'Can view linkRedSocial'), ('can_edit_linkRedSocial', 'Can edit linkRedSocial')]},
        ),
        migrations.AlterModelOptions(
            name='parroquia',
            options={'permissions': [('can_view_parroquia', 'Can view parroquia'), ('can_edit_parroquia', 'Can edit parroquia')]},
        ),
    ]
