# Generated by Django 4.2.16 on 2024-10-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0003_alter_iglesia_options_alter_linkredsocial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaliglesia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicaliglesia',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='historicallinkredsocial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalparroquia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='iglesia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='iglesia',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='linkredsocial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='parroquia',
            name='description',
        ),
        migrations.AddField(
            model_name='historicaliglesia',
            name='sector',
            field=models.TextField(blank=True, null=True, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='sector',
            field=models.TextField(blank=True, null=True, verbose_name='Sector'),
        ),
    ]
