# Generated by Django 4.2.16 on 2024-10-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0006_historicallinkredsocial_iglesia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaliglesia',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicallinkredsocial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalparroquia',
            name='image',
        ),
        migrations.RemoveField(
            model_name='iglesia',
            name='image',
        ),
        migrations.RemoveField(
            model_name='linkredsocial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='parroquia',
            name='image',
        ),
    ]
