# Generated by Django 4.2.16 on 2024-10-24 01:07

from django.db import migrations, models
import iglesias.base


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0007_remove_historicaliglesia_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaliglesia',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[iglesias.base.validar_tamano_imagen], verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='historicalparroquia',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[iglesias.base.validar_tamano_imagen], verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='iglesias/', validators=[iglesias.base.validar_tamano_imagen], verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='iglesias/', validators=[iglesias.base.validar_tamano_imagen], verbose_name='Foto'),
        ),
    ]
