# Generated by Django 4.2.16 on 2024-12-03 07:57

from django.db import migrations, models
import django.db.models.deletion
import iglesias.base


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0008_historicaliglesia_image_historicalparroquia_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaliglesia',
            name='address',
            field=models.CharField(blank=True, default='Pichincha', max_length=200, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='historicaliglesia',
            name='email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicaliglesia',
            name='image',
            field=models.TextField(blank=True, default='hola', max_length=100, validators=[iglesias.base.validar_tamano_imagen], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='historicaliglesia',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1.1, max_digits=9, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='historicaliglesia',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1.1, max_digits=9, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='historicaliglesia',
            name='phone',
            field=models.CharField(blank=True, default='0999999999', max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='historicaliglesia',
            name='priest',
            field=models.CharField(blank=True, default='Livisnton', max_length=100, verbose_name='Sacerdote'),
        ),
        migrations.AlterField(
            model_name='historicaliglesia',
            name='schedule',
            field=models.TextField(blank=True, default='6 a 16', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='historicaliglesia',
            name='sector',
            field=models.TextField(blank=True, default='Cotocollao', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='historicallinkredsocial',
            name='iglesia',
            field=models.ForeignKey(blank=True, db_constraint=False, default=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='iglesias.iglesia'),
        ),
        migrations.AlterField(
            model_name='historicallinkredsocial',
            name='url',
            field=models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', max_length=255, verbose_name='URL de la red social'),
        ),
        migrations.AlterField(
            model_name='historicalparroquia',
            name='image',
            field=models.TextField(blank=True, default='hola', max_length=100, validators=[iglesias.base.validar_tamano_imagen], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='address',
            field=models.CharField(blank=True, default='Pichincha', max_length=200, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='image',
            field=models.ImageField(blank=True, default='hola', upload_to='iglesias/', validators=[iglesias.base.validar_tamano_imagen], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1.1, max_digits=9, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1.1, max_digits=9, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='phone',
            field=models.CharField(blank=True, default='0999999999', max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='priest',
            field=models.CharField(blank=True, default='Livisnton', max_length=100, verbose_name='Sacerdote'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='schedule',
            field=models.TextField(blank=True, default='6 a 16', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='sector',
            field=models.TextField(blank=True, default='Cotocollao', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='linkredsocial',
            name='iglesia',
            field=models.ForeignKey(blank=True, default=20, on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='iglesias.iglesia'),
        ),
        migrations.AlterField(
            model_name='linkredsocial',
            name='url',
            field=models.URLField(blank=True, default='https://www.google.com.ec/?hl=es', max_length=255, verbose_name='URL de la red social'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='image',
            field=models.ImageField(blank=True, default='hola', upload_to='iglesias/', validators=[iglesias.base.validar_tamano_imagen], verbose_name='Foto'),
        ),
    ]
